### ISSUE TITLE
What is the meaning of LD_LIBRARY_PATH？

### ISSUE THREAD

**Issue by chenyufanxin** [skoren/ArrowGrid#1]
Hello, skoren. I want to polish canu aseembly  using your ArrowGrid pipeline on slurm grid. I check the CONFIG file and don't understand the meaning of LD_LIBRARY_PATH? Can you help me ?

**Comment by skoren** [comment]
It is only needed if you have to add some paths to your library environment before running SMRTportal. If your normal environment is enough to run the required commands (pbalign,etc) then you can leave it empty.
