### ISSUE TITLE
Output vcf files and merge them

### ISSUE THREAD

**Issue by aureliendejode** [skoren/ArrowGrid#11]
Hello,
I plan to use merfin after arrow but merfin needs a vcf file.
What I did so far, I modified the consensus.sh script so it also outputs vcf files.
My plan is to merge those vcf together afterwards.
Do you see any caveats in that approach ? Do you think this is compatible with the way arrow_grid is coded ?

Thanks

**Comment by skoren** [comment]
That should work, previously the pipeline was outputting gff but you can just change that to vcf. Since each contig is only processed by one job, it should be fine to merge the vcf files at the end. Feel free to submit a pull request with the update.
