### ISSUE TITLE
size of bam input to ArrowGrid

### ISSUE THREAD

**Issue by elipowel** [skoren/ArrowGrid#2]
Hey Skoren,
I have a Canu assembly That I'd like to throw int ArrowGrid. I have a large subreads.bam with ~1400x coverage whereas my assembly was built with 200x coverage. I attempted to downselect my bam file with samtools to around the same coverage level but the new downselected bam file causes BLASR to freak out when I have tried to run PBalign. I looked at the two files and they look quite different (original bam has an extensive header). Any suggestions on how to make this work?

**Comment by skoren** [comment]
The PacBio bam file has lots of extra information that samtools won't recognize/preserve properly. You need to use PacBio's dataset utility to describe the subset of reads and then instantiate the subset bam file. Take a look at ```subset.sh``` in the repo for an example.

If you wanted to use the exact same reads you input to the assembly, you can use the readNames.txt file from gatekeeper store as input to ArrowGrid. Running it as:
```
sh arrow.sh input.fofn polished asm.fasta readNames.txt
```
will first subset your bams by the readNames.txt list of reads and then polish.
