### ISSUE TITLE
When to run ArrowGrid

### ISSUE THREAD

**Issue by KnudNorNielsen** [skoren/ArrowGrid#4]
Hi,
I hope there is room for a quick basic question from a newbie.
After which step in the workflow: 

- Assembling with Canu
- Scaffolding with SSPACE-LongReads
- Gab filling with PBJelly

Should I run ArrowGrid?

Best regards,
Knud

**Comment by skoren** [comment]
You want to run it at the last step as a minimum. It probably won't hurt to run it after the assembly before scaffolding as it will improve read mapping.
