### ISSUE TITLE
In case of "contigs < NUM_JOBS".

### ISSUE THREAD

**Issue by git4waki** [skoren/ArrowGrid#7]
Dear Dr. Koren, 

I am a user of ArrowGrid and I really appreciate your work.

However, I have few problems for ArrowGrid. For example, in case of "contigs < NUM_JOBS", a number of array jobs is too large for consensus.sh and coverage.sh. And, I think some job number in output file names are not same. 

Then, I modified arrow.sh, consensus.sh, coverage.sh and merge.sh.

If I have no misunderstanding and you would like,  please merge those scripts.

(Note 1: I can test only UGE(SGE) environment.)
(Note 2: Please delete my comments in scripts.)

Sincerely yours,

Kazunori Waki

[ToSkoren.zip](https://github.com/skoren/ArrowGrid/files/2864535/ToSkoren.zip)

**Comment by git4waki** [comment]
Solly, I will confirm a my misunderstanding, later.

**Comment by skoren** [comment]
The script should still work albeit it will submit too many consensus.sh jobs. I've successfully run it with 1 contig and 130+ bam files for example. It will submit 130 consensus jobs but all except the first will exit reporting an out of bounds error. The merge.sh script will still run as it accepts out of bounds as a valid result.

Can you make your changes a pull request so I can review them, I don't think merge.sh should change but I can see arrow.sh changing to submit the min of NUM_JOBS and NUM_CONTIGS.

**Comment by git4waki** [comment]
Dear Dr Koren,

Firstly, I apologise for the delay in replying to you. I have been under the weather for a few days.
And, thanks a lot for your reply!

Because I can not use our internal PC clusters for tests and our data is unpublished data, I will install ArrowGrid to other PC clusters and test scripts (modified for the PC cluster) using a public data befor a pull request (If possible, I want to test using same data as you.). 
If your test data is public data, will you kindly tell me where the data is?

Kazunori Waki

**Comment by skoren** [comment]
Idle
