### ISSUE TITLE
Using arrow_grid on slurm

### ISSUE THREAD

**Issue by aureliendejode** [skoren/ArrowGrid#9]
Hello,

I am trying to use the arrow_grid pipeline on a slurm engine, but I am getting an error:

sh arrow.sh myfiles.fofn saxa.canu /proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155/purge_dup/purged.fa
Running with saxa.canu /proj/snic2020-6-155/canu_new_pacbio_all_third_lib-6-155/purge_dup/purged.fa 
Submitted index job afterok:submission:,afterok:project.,afterok:cluster.,afterok:error
Submitted filter array job afterok:submission:,afterok:project.,afterok:cluster.,afterok:error
Submitted split job afterok:submission:,afterok:project.,afterok:cluster.,afterok:error
Submitted consensus array 
Submitted merge job afterok:submission:,afterok:project.,afterok:cluster.,afterok:error

Do you know what is happening ?

Thank you

**Comment by skoren** [comment]
The output is not giving an explicit error but it should be reporting numbered job ids and not the afterok/etc text. I suspect the submit command is failing because your slurm has some requirements that are missing from the jobs. Post the output files from the submission (`*.submit.out`).

**Comment by aureliendejode** [comment]
here are the *.submit.out files
And yes it is because I need to give a project name to slurm.
Is there a way to do that by modifying a file ?


::::::::::::::
cns.submit.out
::::::::::::::
sbatch: error: Errors in job submission: 
sbatch: error: ERROR 1: Invalid project. 
sbatch: error: Use the flag -A to specify an active project with allocation on this cluster.
sbatch: error: Batch job submission failed: Unspecified error
::::::::::::::
filter.submit.out
::::::::::::::
sbatch: error: Errors in job submission: 
sbatch: error: ERROR 1: Invalid project. 
sbatch: error: Use the flag -A to specify an active project with allocation on this cluster.
sbatch: error: Batch job submission failed: Unspecified error
::::::::::::::
index.submit.out
::::::::::::::
sbatch: error: Errors in job submission: 
sbatch: error: ERROR 1: Invalid project. 
sbatch: error: Use the flag -A to specify an active project with allocation on this cluster.
sbatch: error: Batch job submission failed: Unspecified error
::::::::::::::
merge.submit.out
::::::::::::::
sbatch: error: Errors in job submission: 
sbatch: error: ERROR 1: Invalid project. 
sbatch: error: Use the flag -A to specify an active project with allocation on this cluster.
sbatch: error: Batch job submission failed: Unspecified error
::::::::::::::
split.submit.out
::::::::::::::
sbatch: error: Errors in job submission: 
sbatch: error: ERROR 1: Invalid project. 
sbatch: error: Use the flag -A to specify an active project with allocation on this cluster.
sbatch: error: Batch job submission failed: Unspecified error

**Comment by skoren** [comment]
Yes, you need to modify arrow.sh and change all the qsub commands to add a project name.
